name: Tennis News Bot

on:
  schedule:
    # Executa todos os dias às 8h (horário UTC - Brasília é UTC-3)
    # Para 8h Brasília = 11h UTC
    - cron: '0 11 * * *'
  
  # Permite execução manual
  workflow_dispatch:

jobs:
  send-tennis-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Pull latest rankings
      run: |
        git pull origin main || echo "No changes to pull"
    
    - name: Run tennis news bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python tennis_bot.py
    
    - name: Commit news cache
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Adiciona cache de notícias se existir
        if [ -f "sent_news.json" ]; then
          git add sent_news.json
          git commit -m "🤖 Update news cache" || echo "No changes to commit"
          git push || echo "No changes to push"
        fi
    
    - name: Upload logs (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tennis-bot-logs
        path: |
          *.log
          sent_news.json
        retention-days: 7
